apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.k8s_ns.name }}
spec:
  ports:
  - port: {{ .Values.image.port }}
  selector:
    app: {{ .Release.Name }}
  clusterIP: None