apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.k8s_ns.name }}
spec:
  replicas: {{ .Values.replica.count }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        name: {{ .Release.Name }}
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: "{{ .Values.user.root }}"
        resources:
{{ toYaml .Values.resources | indent 10 }}
        ports:
        - containerPort: {{ .Values.image.port }}
          name: {{ .Release.Name }}
        readinessProbe:
          tcpSocket:
            port: {{ .Values.image.port }}
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: {{ .Values.image.port }}
          initialDelaySeconds: 15
          periodSeconds: 20
        volumeMounts:
        - name: {{ .Release.Name }}-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: {{ .Release.Name }}-persistent-storage
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-pv-claim